### ISSUE TITLE
panic: open ui/templates/layout.html: no such file or directory

### ISSUE THREAD

**Issue by astewart-twist** [hjr265/loadcat#1]
Trying to run this after using the go get installation. Getting the following error:

```
$ .go/bin/loadcatd
panic: open ui/templates/layout.html: no such file or directory

goroutine 1 [running]:
html/template.Must(0x0, 0x7fe6f4f8f078, 0xc20803b530, 0x1)
    /usr/lib/golang/src/html/template/template.go:304 +0x50
github.com/hjr265/loadcat/ui.init()
    .go/src/github.com/hjr265/loadcat/ui/templates.go:10 +0x14a
main.init()
    .go/src/github.com/hjr265/loadcat/cmd/loadcatd/main.go:63 +0x42
```

**Comment by hjr265** [comment]
Hi @astewart-twist.. You need to make sure that the templates (.html files) are available at the path "ui/templates" relative to the current working directory. Which means, after go get'ing this, you will need to cd to `$GOPATH/github.com/hjr265/loadcat` and then run the binary $GOPATH/bin/loadcat` (after go install'ing it of course).

**Comment by astewart-twist** [comment]
Awesome, that worked @hjr265, thanks!  (I'm a bit new to go).  

This is very slick!

**Comment by boukalamc** [comment]
Use the relative path to the current working directory (Exp. "ui/templates/home.html"), and when you start your web application you must be in the root folder (folder of main.go).
